/**
 * config.sqf
 *
 * LICENSE: This file is subject to the terms and conditions defined in
 * file "LICENSE.md", which is part of this source code package.
 *
 * @package    Supremacy Framework
 * @author     Mark Eliasen <https://github.com/MrEliasen>
 * @copyright  2015 Mark Eliasen
 * @license    MIT License
 * @link       https://github.com/MrEliasen/SupremacyFramework
 */
SPMC_fnc_config = compileFinal "
switch (_this select 0) do {
    case ""debug_mode"": {
        true;
    };

    case ""spawn_type"": {
        ""select_city"";
    };

    case ""loot_crate_limit"": {
        10;
    };

    case ""loot_vehicle_limit"": {
        10;
    };

    case ""loot_stationery_limit"": {
        10;
    };

    case ""airdrop_interval"": {
        10;
    };

    case ""spawn_excludes"": {
        [
            ""system_safezone"",
            ""spawn_exclude_1"",
            ""spawn_exclude_2"",
            ""spawn_exclude_3"",
            ""spawn_exclude_4"",
            ""spawn_exclude_5"",
            ""spawn_exclude_6""
        ];
    };

    case ""spawn_points"": {
        [
            [
                ""spawn_1"",
                ""Molos""
            ],
            [
                ""spawn_2"",
                ""Sofia""
            ],
            [
                ""spawn_3"",
                ""Paros/Kalochori""
            ],
            [
                ""spawn_4"",
                ""Rodopoli""
            ],
            [
                ""spawn_5"",
                ""Charkia""
            ],
            [
                ""spawn_6"",
                ""Pyrgos""
            ],
            [
                ""spawn_7"",
                ""Chalkela""
            ],
            [
                ""spawn_8"",
                ""Panagia""
            ],
            [
                ""spawn_9"",
                ""Feres""
            ],
            [
                ""spawn_10"",
                ""Selakano""
            ],
            [
                ""spawn_11"",
                ""Loannia/Delfinaki""
            ],
            [
                ""spawn_12"",
                ""Athira""
            ],
            [
                ""spawn_13"",
                ""Telos""
            ],
            [
                ""spawn_14"",
                ""Frini""
            ],
            [
                ""spawn_15"",
                ""Gravia""
            ],
            [
                ""spawn_16"",
                ""Galati""
            ],
            [
                ""spawn_17"",
                ""Agios Dionysios""
            ],
            [
                ""spawn_18"",
                ""Lakka/Stavros/Neochori""
            ],
            [
                ""spawn_19"",
                ""Alikampos/Poliakko/Katalaki""
            ],
            [
                ""spawn_20"",
                ""Therisa""
            ],
            [
                ""spawn_21"",
                ""Zaros""
            ],
            [
                ""spawn_22"",
                ""Syrta""
            ],
            [
                ""spawn_23"",
                ""Kore""
            ],
            [
                ""spawn_24"",
                ""Negades""
            ],
            [
                ""spawn_25"",
                ""Panochori""
            ],
            [
                ""spawn_26"",
                ""Neri""
            ],
            [
                ""spawn_27"",
                ""Ifestiona""
            ],
            [
                ""spawn_28"",
                ""Abdera""
            ],
            [
                ""spawn_29"",
                ""Dorlda""
            ],
            [
                ""spawn_30"",
                ""Oreokastro""
            ],
            [
                ""spawn_31"",
                ""Anthrakia""
            ]
        ];
    };

    case ""drop_zones"": {
        [
            ""drop_zone_1"",
            ""drop_zone_2"",
            ""drop_zone_3"",
            ""drop_zone_4"",
            ""drop_zone_5"",
            ""drop_zone_6"",
            ""drop_zone_7"",
            ""drop_zone_8"",
            ""drop_zone_9"",
            ""drop_zone_10""
        ];
    };

    case ""spawn_items"": {
        [
            ""U_IG_Guerilla1_1"",
            ""V_BandollierB_khk"",
            ""B_Kitbag_rgr"",
            ""H_Beret_grn"",
            ""hgun_ACPC2_F"",
            [
                ""9Rnd_45ACP_Mag"",
                ""9Rnd_45ACP_Mag"",
                ""9Rnd_45ACP_Mag""
            ],
            [
                ""FirstAidKit"",
                ""HandGrenade""
            ],
            [
                ""ItemMap"",
                ""ItemCompass"",
                ""ItemGPS"",
                ""ItemWatch"",
                ""NVGoggles""
            ]
        ];
    };

    case ""equip_items"": {
        [
            ""Binocular"",
            ""ToolKit"",
            ""FirstAidKit"",
            ""Medikit"",
            ""ItemWatch"",
            ""ItemCompass"",
            ""ItemGPS"",
            ""ItemRadio"",
            ""ItemMap"",
            ""Rangefinder"",
            ""NVGoggles""
        ];
    };

    case ""airdrop_weapons"";
    case ""equip_weapons"": {
        [
            ""arifle_Katiba_C_F"",
            ""arifle_Katiba_F"",
            ""arifle_Katiba_GL_F"",
            ""arifle_Mk20C_F"",
            ""arifle_Mk20C_plain_F"",
            ""arifle_Mk20_F"",
            ""arifle_Mk20_GL_F"",
            ""arifle_Mk20_GL_plain_F"",
            ""arifle_Mk20_plain_F"",
            ""arifle_MXC_Black_F"",
            ""arifle_MXC_F"",
            ""arifle_MXM_Black_F"",
            ""arifle_MXM_F"",
            ""arifle_MX_Black_F"",
            ""arifle_MX_F"",
            ""arifle_MX_GL_Black_F"",
            ""arifle_MX_GL_F"",
            ""arifle_MX_SW_Black_F"",
            ""arifle_MX_SW_F"",
            ""arifle_SDAR_F"",
            ""arifle_TRG20_F"",
            ""arifle_TRG21_F"",
            ""arifle_TRG21_GL_F"",
            ""hgun_ACPC2_F"",
            ""hgun_P07_F"",
            ""hgun_PDW2000_F"",
            ""hgun_Pistol_heavy_01_F"",
            ""hgun_Pistol_heavy_02_F"",
            ""hgun_Pistol_Signal_F"",
            ""hgun_Rook40_F"",
            ""launch_B_Titan_F"",
            ""launch_B_Titan_short_F"",
            ""launch_I_Titan_F"",
            ""launch_I_Titan_short_F"",
            ""launch_NLAW_F"",
            ""launch_O_Titan_F"",
            ""launch_O_Titan_short_F"",
            ""launch_RPG32_F"",
            ""launch_Titan_F"",
            ""launch_Titan_short_F"",
            ""LMG_Mk200_F"",
            ""LMG_Zafir_F"",
            ""MMG_01_hex_F"",
            ""MMG_01_tan_F"",
            ""MMG_02_black_F"",
            ""MMG_02_camo_F"",
            ""MMG_02_sand_F"",
            ""SMG_01_F"",
            ""SMG_02_F"",
            ""srifle_DMR_01_F"",
            ""srifle_DMR_02_camo_F"",
            ""srifle_DMR_02_F"",
            ""srifle_DMR_02_sniper_F"",
            ""srifle_DMR_03_F"",
            ""srifle_DMR_03_khaki_F"",
            ""srifle_DMR_03_multicam_F"",
            ""srifle_DMR_03_tan_F"",
            ""srifle_DMR_03_woodland_F"",
            ""srifle_DMR_04_F"",
            ""srifle_DMR_04_Tan_F"",
            ""srifle_DMR_05_blk_F"",
            ""srifle_DMR_05_hex_F"",
            ""srifle_DMR_05_tan_f"",
            ""srifle_DMR_06_camo_F"",
            ""srifle_DMR_06_camo_khs_F"",
            ""srifle_DMR_06_olive_F"",
            ""srifle_EBR_F"",
            ""srifle_GM6_camo_F"",
            ""srifle_GM6_F"",
            ""srifle_LRR_camo_F"",
            ""srifle_LRR_F""
        ];
    };

    case ""equip_throwables"": {
        [
            ""HandGrenade"",
            ""MiniGrenade"",
            ""SmokeShell"",
            ""SmokeShellYellow"",
            ""SmokeShellGreen"",
            ""SmokeShellRed"",
            ""SmokeShellPurple"",
            ""SmokeShellOrange"",
            ""SmokeShellBlue"",
            ""Chemlight_green"",
            ""Chemlight_red"",
            ""Chemlight_yellow"",
            ""Chemlight_blue"",
            ""I_IR_Grenade""
        ];
    };
    case ""equip_clothes"": {
        [
            ""U_I_CombatUniform"",
            ""U_I_FullGhillie_ard"",
            ""U_I_FullGhillie_lsh"",
            ""U_I_FullGhillie_sard"",
            ""U_I_pilotCoveralls"",
            ""U_I_CombatUniform_tshirt"",
            ""U_I_CombatUniform_shortsleeve"",
            ""U_I_HeliPilotCoveralls"",
            ""U_I_OfficerUniform"",
            ""U_I_Wetsuit"",
            ""U_KerryBody"",
            ""U_AttisBody"",
            ""U_AntigonaBody"",
            ""U_C_Novak"",
            ""U_OI_Scientist"",
            ""U_IG_Guerilla1_1"",
            ""U_IG_Guerilla2_1"",
            ""U_IG_Guerilla2_2"",
            ""U_IG_Guerilla2_3"",
            ""U_IG_Guerilla3_1"",
            ""U_IG_Guerilla3_2"",
            ""U_IG_leader"",
            ""U_IG_Guerrilla_6_1"",
            ""U_I_GhillieSuit"",
            ""U_I_FullGhillie_ard"",
            ""U_I_FullGhillie_lsh"",
            ""U_I_FullGhillie_sard"",
            ""U_I_GhillieSuit""
        ];
    };

    case ""equip_hats"": {
        [
            ""H_HelmetB"",
            ""H_HelmetB_camo"",
            ""H_HelmetB_paint"",
            ""H_HelmetB_light"",
            ""H_Booniehat_khk"",
            ""H_Booniehat_oli"",
            ""H_Booniehat_indp"",
            ""H_Booniehat_mcamo"",
            ""H_Booniehat_grn"",
            ""H_Booniehat_tan"",
            ""H_Booniehat_dirty"",
            ""H_Booniehat_dgtl"",
            ""H_Booniehat_khk_hs"",
            ""H_HelmetB_plain_mcamo"",
            ""H_HelmetB_plain_blk"",
            ""H_HelmetSpecB"",
            ""H_HelmetSpecB_paint1"",
            ""H_HelmetSpecB_paint2"",
            ""H_HelmetSpecB_blk"",
            ""H_HelmetSpecB_snakeskin"",
            ""H_HelmetSpecB_sand"",
            ""H_HelmetIA"",
            ""H_HelmetIA_net"",
            ""H_HelmetIA_camo"",
            ""H_Helmet_Kerry"",
            ""H_HelmetB_grass"",
            ""H_HelmetB_snakeskin"",
            ""H_HelmetB_desert"",
            ""H_HelmetB_black"",
            ""H_HelmetB_sand"",
            ""H_Cap_red"",
            ""H_Cap_blu"",
            ""H_Cap_oli"",
            ""H_Cap_headphones"",
            ""H_Cap_tan"",
            ""H_Cap_blk"",
            ""H_Cap_blk_CMMG"",
            ""H_Cap_brn_SPECOPS"",
            ""H_Cap_tan_specops_US"",
            ""H_Cap_khaki_specops_UK"",
            ""H_Cap_grn"",
            ""H_Cap_grn_BI"",
            ""H_Cap_blk_Raven"",
            ""H_Cap_blk_ION"",
            ""H_Cap_oli_hs"",
            ""H_Cap_press"",
            ""H_Cap_usblack"",
            ""H_Cap_surfer"",
            ""H_Cap_police"",
            ""H_HelmetCrew_B"",
            ""H_HelmetCrew_O"",
            ""H_HelmetCrew_I"",
            ""H_PilotHelmetFighter_B"",
            ""H_PilotHelmetFighter_O"",
            ""H_PilotHelmetFighter_I"",
            ""H_PilotHelmetHeli_B"",
            ""H_PilotHelmetHeli_O"",
            ""H_PilotHelmetHeli_I"",
            ""H_CrewHelmetHeli_B"",
            ""H_CrewHelmetHeli_O"",
            ""H_CrewHelmetHeli_I"",
            ""H_HelmetO_ocamo"",
            ""H_HelmetLeaderO_ocamo"",
            ""H_MilCap_ocamo"",
            ""H_MilCap_mcamo"",
            ""H_MilCap_oucamo"",
            ""H_MilCap_rucamo"",
            ""H_MilCap_gry"",
            ""H_MilCap_dgtl"",
            ""H_MilCap_blue"",
            ""H_HelmetB_light_grass"",
            ""H_HelmetB_light_snakeskin"",
            ""H_HelmetB_light_desert"",
            ""H_HelmetB_light_black"",
            ""H_HelmetB_light_sand"",
            ""H_BandMask_blk"",
            ""H_BandMask_khk"",
            ""H_BandMask_reaper"",
            ""H_BandMask_demon"",
            ""H_HelmetO_oucamo"",
            ""H_HelmetLeaderO_oucamo"",
            ""H_HelmetSpecO_ocamo"",
            ""H_HelmetSpecO_blk"",
            ""H_Bandanna_surfer"",
            ""H_Bandanna_khk"",
            ""H_Bandanna_khk_hs"",
            ""H_Bandanna_cbr"",
            ""H_Bandanna_sgg"",
            ""H_Bandanna_sand"",
            ""H_Bandanna_surfer_blk"",
            ""H_Bandanna_surfer_grn"",
            ""H_Bandanna_gry"",
            ""H_Bandanna_blu"",
            ""H_Bandanna_camo"",
            ""H_Bandanna_mcamo"",
            ""H_Shemag_khk"",
            ""H_Shemag_tan"",
            ""H_Shemag_olive"",
            ""H_Shemag_olive_hs"",
            ""H_ShemagOpen_khk"",
            ""H_ShemagOpen_tan"",
            ""H_Beret_blk"",
            ""H_Beret_blk_POLICE"",
            ""H_Beret_red"",
            ""H_Beret_grn"",
            ""H_Beret_grn_SF"",
            ""H_Beret_brn_SF"",
            ""H_Beret_ocamo"",
            ""H_Beret_02"",
            ""H_Beret_Colonel"",
            ""H_Watchcap_blk"",
            ""H_Watchcap_cbr"",
            ""H_Watchcap_khk"",
            ""H_Watchcap_camo"",
            ""H_Watchcap_sgg"",
            ""H_TurbanO_blk"",
            ""H_StrawHat"",
            ""H_StrawHat_dark"",
            ""H_Hat_blue"",
            ""H_Hat_brown"",
            ""H_Hat_camo"",
            ""H_Hat_grey"",
            ""H_Hat_checker"",
            ""H_Hat_tan"",
            ""H_Cap_marshal""
        ];
    };

    case ""equip_glasses"": {
        [
            ""G_Spectacles"",
            ""G_Spectacles_Tinted"",
            ""G_Combat"",
            ""G_Lowprofile"",
            ""G_Shades_Black"",
            ""G_Shades_Green"",
            ""G_Shades_Red"",
            ""G_Squares"",
            ""G_Squares_Tinted"",
            ""G_Sport_BlackWhite"",
            ""G_Sport_Blackyellow"",
            ""G_Sport_Greenblack"",
            ""G_Sport_Checkered"",
            ""G_Sport_Red"",
            ""G_Tactical_Black"",
            ""G_Aviator"",
            ""G_Lady_Mirror"",
            ""G_Lady_Dark"",
            ""G_Lady_Red"",
            ""G_Lady_Blue"",
            ""G_Diving"",
            ""G_B_Diving"",
            ""G_O_Diving"",
            ""G_I_Diving"",
            ""G_Balaclava_blk"",
            ""G_Balaclava_oli"",
            ""G_Balaclava_combat"",
            ""G_Balaclava_lowprofile"",
            ""G_Bandanna_blk"",
            ""G_Bandanna_oli"",
            ""G_Bandanna_khk"",
            ""G_Bandanna_tan"",
            ""G_Bandanna_beast"",
            ""G_Bandanna_shades"",
            ""G_Bandanna_sport"",
            ""G_Bandanna_aviator"",
            ""G_Shades_Blue"",
            ""G_Sport_Blackred"",
            ""G_Tactical_Clear""
        ];
    };

    case ""equip_vests"": {
        [
            ""V_Rangemaster_belt"",
            ""V_BandollierB_khk"",
            ""V_BandollierB_cbr"",
            ""V_BandollierB_rgr"",
            ""V_BandollierB_blk"",
            ""V_BandollierB_oli"",
            ""V_Chestrig_khk"",
            ""V_Chestrig_rgr"",
            ""V_Chestrig_blk"",
            ""V_Chestrig_oli"",
            ""V_TacVest_khk"",
            ""V_TacVest_brn"",
            ""V_TacVest_oli"",
            ""V_TacVest_blk"",
            ""V_TacVest_camo"",
            ""V_TacVest_blk_POLICE"",
            ""V_TacVestIR_blk"",
            ""V_TacVestCamo_khk"",
            ""V_HarnessO_brn"",
            ""V_HarnessOGL_brn"",
            ""V_HarnessO_gry"",
            ""V_HarnessOGL_gry"",
            ""V_HarnessOSpec_brn"",
            ""V_HarnessOSpec_gry"",
            ""V_I_G_resistanceLeader_F"",
            ""V_Press_F"",
            ""V_PlateCarrier_Kerry"",
            ""V_PlateCarrierL_CTRG"",
            ""V_PlateCarrierH_CTRG"",
            ""V_PlateCarrierIA1_dgtl"",
            ""V_PlateCarrierIA2_dgtl"",
            ""V_PlateCarrierIAGL_dgtl"",
            ""V_PlateCarrierIAGL_oli"",
            ""V_PlateCarrier1_rgr"",
            ""V_PlateCarrier2_rgr"",
            ""V_PlateCarrier2_blk"",
            ""V_PlateCarrier3_rgr"",
            ""V_PlateCarrierGL_rgr"",
            ""V_PlateCarrierGL_blk"",
            ""V_PlateCarrierGL_mtp"",
            ""V_PlateCarrier1_blk"",
            ""V_PlateCarrierSpec_rgr"",
            ""V_PlateCarrierSpec_blk"",
            ""V_PlateCarrierSpec_mtp""
        ];
    };

    case ""equip_backpacks"": {
        [
            ""B_AssaultPack_khk"",
            ""B_AssaultPack_dgtl"",
            ""B_AssaultPack_rgr"",
            ""B_AssaultPack_sgg"",
            ""B_AssaultPack_blk"",
            ""B_AssaultPack_cbr"",
            ""B_AssaultPack_mcamo"",
            ""B_AssaultPack_oc"",
            ""B_Kitbag_rgr"",
            ""B_Kitbag_mcamo"",
            ""B_Kitbag_sgg"",
            ""B_Kitbag_cbr"",
            ""B_TacticalPack_rgr"",
            ""B_TacticalPack_mcamo"",
            ""B_TacticalPack_ocamo"",
            ""B_TacticalPack_blk"",
            ""B_TacticalPack_oli"",
            ""B_FieldPack_khk"",
            ""B_FieldPack_ocamo"",
            ""B_FieldPack_oucamo"",
            ""B_FieldPack_cbr"",
            ""B_FieldPack_blk"",
            ""B_FieldPack_oli"",
            ""B_Carryall_ocamo"",
            ""B_Carryall_oucamo"",
            ""B_Carryall_mcamo"",
            ""B_Carryall_khk"",
            ""B_Carryall_cbr"",
            ""B_Carryall_oli"",
            ""B_Bergen_sgg"",
            ""B_Bergen_mcamo"",
            ""B_Bergen_rgr"",
            ""B_Bergen_blk"",
            ""B_OutdoorPack_blk"",
            ""B_OutdoorPack_tan"",
            ""B_OutdoorPack_blu"",
            ""B_HuntingBackpack"",
            ""B_Parachute""
        ];
    };

    case ""equip_attachments"": {
        [
            [
                ""optic_Arco"",
                ""optic_Hamr"",
                ""optic_Aco"",
                ""optic_ACO_grn"",
                ""optic_Aco_smg"",
                ""optic_ACO_grn_smg"",
                ""optic_Holosight"",
                ""optic_Holosight_smg"",
                ""optic_SOS"",
                ""optic_MRCO"",
                ""optic_NVS"",
                ""optic_Nightstalker"",
                ""optic_tws"",
                ""optic_tws_mg"",
                ""optic_DMS"",
                ""optic_Yorris"",
                ""optic_MRD"",
                ""optic_LRPS"",
                ""optic_AMS"",
                ""optic_AMS_khk"",
                ""optic_AMS_snd"",
                ""optic_KHS_blk"",
                ""optic_KHS_hex"",
                ""optic_KHS_old"",
                ""optic_KHS_tan""
            ],
            [
                ""bipod_01_F_snd"",
                ""bipod_01_F_blk"",
                ""bipod_01_F_mtp"",
                ""bipod_02_F_blk"",
                ""bipod_02_F_tan"",
                ""bipod_02_F_hex"",
                ""bipod_03_F_blk"",
                ""bipod_03_F_oli""
            ],
            [
                ""muzzle_snds_H"",
                ""muzzle_snds_L"",
                ""muzzle_snds_M"",
                ""muzzle_snds_B"",
                ""muzzle_snds_H_MG"",
                ""muzzle_snds_H_SW"",
                ""muzzle_snds_acp"",
                ""muzzle_snds_338_black"",
                ""muzzle_snds_338_green"",
                ""muzzle_snds_338_sand"",
                ""muzzle_snds_93mmg"",
                ""muzzle_snds_93mmg_tan""
            ],
            [
                ""acc_flashlight"",
                ""acc_pointer_IR""
            ]
        ];
    };

    case ""ground_vehicles"": {
        [
            ""B_APC_Tracked_01_rcws_F"",
            ""B_APC_Tracked_01_CRV_F"",
            ""B_APC_Tracked_01_AA_F"",
            ""B_MBT_01_cannon_F"",
            ""B_MBT_01_arty_F"",
            ""B_MBT_01_mlrs_F"",
            ""B_MRAP_01_F"",
            ""B_MRAP_01_gmg_F"",
            ""B_MRAP_01_hmg_F"",
            ""B_G_Offroad_01_F"",
            ""B_G_Offroad_01_armed_F"",
            ""B_Quadbike_01_F"",
            ""B_G_Quadbike_01_F"",
            ""B_G_Van_01_fuel_F"",
            ""B_G_Van_01_transport_F"",
            ""B_APC_Wheeled_01_cannon_F"",
            ""B_MBT_01_TUSK_F"",
            ""O_APC_Tracked_02_AA_F"",
            ""O_APC_Tracked_02_cannon_F"",
            ""O_MBT_02_cannon_F"",
            ""O_MBT_02_arty_F"",
            ""O_MRAP_02_F"",
            ""O_MRAP_02_hmg_F"",
            ""O_MRAP_02_gmg_F"",
            ""O_G_Offroad_01_armed_F"",
            ""O_G_Offroad_01_F"",
            ""O_Truck_02_covered_F"",
            ""O_Truck_02_transport_F"",
            ""O_Truck_02_fuel_F"",
            ""O_Truck_02_medical_F"",
            ""O_APC_Wheeled_02_rcws_F"",
            ""I_APC_tracked_03_cannon_F"",
            ""I_MBT_03_cannon_F"",
            ""I_MRAP_03_F"",
            ""I_MRAP_03_hmg_F"",
            ""I_MRAP_03_gmg_F"",
            ""I_Truck_02_ammo_F"",
            ""I_APC_Wheeled_03_cannon_F"",
            ""C_Offroad_01_F"",
            ""C_Hatchback_01_F"",
            ""C_Hatchback_01_sport_F"",
            ""C_SUV_01_F"",
            ""C_Van_01_box_F""
        ];
    };

    case ""air_vehicles"": {
        [
            ""B_Heli_Light_01_F"",
            ""B_Heli_Light_01_armed_F"",
            ""O_Heli_Light_02_F"",
            ""O_Heli_Light_02_unarmed_F"",   
            ""B_Heli_Attack_01_F"",   
            ""O_Heli_Attack_02_F"",
            ""O_Heli_Attack_02_black_F"",
            ""B_Heli_Transport_01_F"",
            ""B_Heli_Transport_01_camo_F"",
            ""I_Heli_Transport_02_F"", 
            ""I_Heli_light_03_unarmed_F"",
            ""I_Heli_light_03_F"",
            ""B_Plane_CAS_01_F"",  
            ""O_Plane_CAS_02_F"",
            ""I_Plane_Fighter_03_CAS_F"",
            ""I_Plane_Fighter_03_AA_F""
        ];
    };

    case ""water_vehicles"": {
        [
            ""C_Boat_Civil_01_F"",
            ""C_Rubberboat"",
            ""O_Boat_Transport_01_F"",
            ""O_Boat_Armed_01_hmg_F"",
            ""O_G_Boat_Transport_01_F"",
            ""B_Boat_Armed_01_minigun_F"",
            ""B_Boat_Transport_01_F"",
            ""I_Boat_Armed_01_minigun_F"",
            ""I_Boat_Transport_01_F"",
            ""I_G_Boat_Transport_01_F""
        ];
    };

    case ""stationery_items"": {
        [
            ""O_static_AA_F"",
            ""O_static_AT_F"",
            ""O_HMG_01_high_F"",
            ""O_GMG_01_high_F""
        ];
    };

    case ""item_prices"": {
        [];
    };
};";
publicVariable "SPMC_fnc_config";